SELECT  [Unique Record ID]
      
      ,[Days between Completed IP Spell and ED Presentation]
      
      ,[Patient ICS]
      ,[Local MH Trust]
     
      ,[Der_Provider_Name]
      ,[Der_Provider_Site_Code]
      
      ,[Provider ICB]
      
      ,[Arrival_Date]
      ,[ArrivalDate FY]
      
      ,[Total Time In ED]
      ,[Time Grouper]
   
   ,[Known to MH Services Flag]
      --,[MH ED Chief Complaint SNOMED Code]
      --,[MH ED Chief Complaint Description]
      --,[MH ED Injury Intent SNOMED Code]
      --,[MH ED Injury Intent Description]
      --,[MH All ED SNOMED Diagnosis Codes]
      --,[MH Primary SNOMED Diagnosis Code]
      --,[MH Primary Diagnosis Description]
      --,[Secondary Diagnosis Code]
      --,[Secondary Diagnosis Description]
      --,[Third Diagnosis Code]
      --,[Third Diagnosis Description]
      --,[Fourth Diagnosis Code]
      --,[Fourth Diagnosis Description]
      --,[Reduction in Inappropriate Flag]
      --,[Comorbidity_01]
      --,[Comorbidity_02]
      --,[Comorbidity_03]
      --,[Comorbidity_04]
      --,[Referred_To_Service_01]
      --,[Service_Request_Date_01]
      --,[Service_Request_Time_01]
      --,[Service_Assessment_Date_01]
      --,[Service_Assessment_Time_01]
      --,[Referred_To_Service_02]
      --,[Service_Request_Date_02]
      --,[Service_Request_Time_02]
      --,[Service_Assessment_Date_02]
      --,[Service_Assessment_Time_02]
      --,[Referred_To_Service_03]
      --,[Service_Request_Date_03]
      --,[Service_Request_Time_03]
      --,[Service_Assessment_Date_03]
      --,[Service_Assessment_Time_03]
      --,[Referred_To_Service_04]
      --,[Service_Request_Date_04]
      --,[Service_Request_Time_04]
      --,[Service_Assessment_Date_04]
      --,[Service_Assessment_Time_04]
      --,[DischargeDestination]
      --,[Discharge Followup Description]
      --,[Chief Complaint Flag]
      --,[Injury Flag]
      --,[Injury Intent Flag]
      --,[Diagnosis Flag]
      --,[Mental Health Presentation Flag]
      --,[Self Harm Flag]
  FROM [PATLondon].[ECDS_All_Presentations_London]
  where [ED Presentation within 28 days of Completed IP SPell] = 1
  and [Mental Health Presentation Flag] = 1
