USE [ETL_Local_PROD]
GO
/****** Object:  StoredProcedure [dbo].[AT__Activity_Data]    Script Date: 14/06/2021 12:10:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO




alter PROCEDURE [dbo].[AT_Rebuild_Actiity_Table_Indexes] 
-- Amended for PD Upgrade
AS
BEGIN
/****** Object:  Index [NonClusteredIndex-20210614-115642]    Script Date: 14/06/2021 12:03:51 ******/
DROP INDEX [NonClusteredIndex-20210614-115642] ON [dbo].[AT_CarePlanData]
 
SET ANSI_PADDING ON
 

--Careplandata table indexes
--NonClusteredIndex-20210614-120638

CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20210614-115642] ON [dbo].[AT_CarePlanData]
(
	[AuditID] ASC,
	[CMC_ID] ASC,
	[OverAllOrder] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]



DROP INDEX [NonClusteredIndex-20210614-115741] ON [dbo].[AT_CarePlanData]
 

SET ANSI_PADDING ON
 


CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20210614-115741] ON [dbo].[AT_CarePlanData]
(
	[AuditID] ASC,
	[CMC_ID] ASC,
	[DeptEnterpriseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


DROP INDEX [NonClusteredIndex-20210614-120638] ON [dbo].[AT_TEam_Activity_Report_Data_Table]
 

SET ANSI_PADDING ON
 


CREATE NONCLUSTERED INDEX [NonClusteredIndex-20210614-120638] ON [dbo].[AT_TEam_Activity_Report_Data_Table]
(
	[ActionTime] ASC,
	[EnterpriseID] ASC 
 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]




DROP INDEX [NonClusteredIndex-20210614-121902] ON [dbo].[AT_CarePlanViewData]
 
SET ANSI_PADDING ON
 

 
CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20210614-121902] ON [dbo].[AT_CarePlanViewData]
(
	[CMC_ID] ASC,
	[AuditID] ASC,
	[ActionTime] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]



DROP INDEX [NonClusteredIndex-20210614-122032] ON [dbo].[AT_CarePlanViewData]
 
CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20210614-122032] ON [dbo].[AT_CarePlanViewData]
(
	[CMC_ID] ASC,
	[AuditID] ASC,
	[EnterpriseID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]



 End

